
# What is PyTorch?

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch, matplotlib, numpy as np
%matplotlib inline

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5,3)
print(x)

tensor([[ 9.9354e-38,  4.5747e-41,  9.9355e-38],
        [ 4.5747e-41,  9.3948e-38,  4.5747e-41],
        [-1.0976e-11,  3.0662e-41,  1.0089e-42],
        [ 0.0000e+00,  8.9683e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.8545e+25]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.1508, 0.7179, 0.7431],
        [0.6917, 0.9186, 0.1138],
        [0.5101, 0.3057, 0.8739],
        [0.2368, 0.5248, 0.7228],
        [0.2571, 0.9209, 0.2342]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods reuse properties of the input tensor, e.g. dtype, unless
new values are provided.

In [10]:
x = x.new_ones(5,3,dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x,dtype=torch.float)   # override dtype
print(x)                                    # result has the same size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3911, -1.2004, -1.1698],
        [-0.0216, -0.3579, -1.7279],
        [ 0.1533,  1.5864, -0.4136],
        [ 1.2997,  1.2311,  0.9447],
        [ 1.1638, -0.6565,  0.3091]])
torch.Size([5, 3])


#### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [12]:
# Syntax 1
y = torch.rand(5, 3)
print(x + y)

# Syntax 2
print(torch.add(x, y))

# Syntax 3
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# Syntax 4
y.add_(x)
print(y)

tensor([[ 0.9288, -0.5901, -1.0661],
        [ 0.1068,  0.2418, -1.0126],
        [ 0.6101,  2.5262,  0.5338],
        [ 1.8472,  2.2079,  1.8164],
        [ 1.4233, -0.4811,  0.5903]])
tensor([[ 0.9288, -0.5901, -1.0661],
        [ 0.1068,  0.2418, -1.0126],
        [ 0.6101,  2.5262,  0.5338],
        [ 1.8472,  2.2079,  1.8164],
        [ 1.4233, -0.4811,  0.5903]])
tensor([[ 0.9288, -0.5901, -1.0661],
        [ 0.1068,  0.2418, -1.0126],
        [ 0.6101,  2.5262,  0.5338],
        [ 1.8472,  2.2079,  1.8164],
        [ 1.4233, -0.4811,  0.5903]])
tensor([[ 0.9288, -0.5901, -1.0661],
        [ 0.1068,  0.2418, -1.0126],
        [ 0.6101,  2.5262,  0.5338],
        [ 1.8472,  2.2079,  1.8164],
        [ 1.4233, -0.4811,  0.5903]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_() will change x.</p></div>

If you want to resize/reshape tensor, you can use ``torch.view``:

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one-element tensor, use ``.item()`` to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0288])
0.028803542256355286


## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [15]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


See how the numpy array changed in value:

In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor:

In [18]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.

In [19]:
# run this cell only if CUDA is available
# We will use torch.device objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ".to("cuda")"
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # .to can also change dtype together!

## More Tensor Operations

In [20]:
v1 = torch.Tensor(2,3)           # An un-initialized torch.FloatTensor of size 2x3
v2 = torch.Tensor([[1,2],[4,5]]) # A Tensor initialized with a specific array
v3 = torch.LongTensor([1,2,3])   # A Tensor of type Long
print(v1,"\n",v2,"\n",v3)

tensor([[0.0000e+00, 0.0000e+00, 7.8971e-37],
        [4.5747e-41, 8.9683e-44, 0.0000e+00]]) 
 tensor([[1., 2.],
        [4., 5.]]) 
 tensor([1, 2, 3])


In [6]:
v = torch.rand(2,3)             # Initialize with random number (uniform distribution)
v = torch.randn(2,3)            # With normal distribution (SD=1, mean=0)
v = torch.randperm(4)           # Size 4. Random permutation of integers from 0 to 3
eye = torch.eye(3)              # Create an identity 3x3 tensor
v = torch.ones(10)              # A tensor of size 10 containing all ones
v = torch.ones(2,1,2,1)         # Size 2x1x2x1
v = torch.ones_like(eye)        # A tensor with same shape as eye. Fill it with 1.
v = torch.zeros(10)             # A tensor of size 10 containing all zeros
v = torch.arange(5)             # similar to range(5) but creating a Tensor
v = torch.arange(0,5,step=1)    # Size 5. Similar to range(0, 5, 1)

v = torch.linspace(1,10,steps=10)            # Create a Tensor with 10 linear points for (1,10) inclusively
v = torch.logspace(start=-10,end=10,steps=5) # Size 5: 1.0e-10 1.0e-05 1.0e+00, 1.0e+05, 1.0e+10

In [21]:
v = torch.ones(3, 3)
print(v)
v[1].fill_(2)
print(v)
v[2].fill_(3)
print(v)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


#### Indexing, Slicing, Joining, Mutating

In [22]:
# Concatenation
torch.cat((x,x,x),0) # Concatenate in the 0 dimension

# Gather element
# torch.gather(input, dim, index, out=None)
r = torch.gather(v,1,torch.LongTensor([[0,1],[1,0],[2,1]]))

# Split an array into 3 chunks
r = torch.chunk(v, 3)

# Index select
indices = torch.LongTensor([0,2])
r = torch.index_select(v,1,indices) # Select element 0 and 2 for each dimension 1.

# Masked select
mask = v.ge(3)
r = torch.masked_select(v,mask)

# [i,j] index for non-zero elements
r = torch.nonzero(v)

# Split an array into chunks of at most size 2
r = torch.split(v,2)

t = torch.ones(2,1,2,1) # Size 2x1x2x1
r = torch.squeeze(t)    # Size 2x2
r = torch.squeeze(t,1)  # Squeeze dimension 1: Size 2x2x1

# Stack
r = torch.stack((v,v))

# Flatten a TensorFlow and return elements with given indexes
r = torch.take(v,torch.LongTensor([0,4,2]))

# Transpose dim 0 and 1
r = torch.transpose(v,0,1)

# Un-squeeze a dimension
x = torch.Tensor([1,2,3])
r = torch.unsqueeze(x,0)    # Size: 1x3
r = torch.unsqueeze(x,1)    # Size: 3x1

c = torch.ByteTensor([0,1,1,0])

#### Distributions

In [24]:
# Uniform distributed
r = torch.Tensor(2,2).uniform_(0,1)

# bernoulli
r = torch.bernoulli(r)   # Size: 2x2. Bernoulli with probability p stored in elements of r

# Multinomial
w = torch.Tensor([0,4,8,2]) # Create a tensor of weights
r = torch.multinomial(w,4,replacement=True) # Size 4: 3, 2, 1, 2

# Normal distribution
# From 10 means and SD
r = torch.distributions.normal.Normal(loc=torch.tensor([0.0]),scale=torch.tensor([1.0])) # Size 10

#### Reduction operations

In [25]:
# Accumulate sum
r = torch.cumsum(v,dim=0)

# L-P norm
r = torch.dist(v,v+3,p=2)  # L-2 norm: ((3^2)*9)^(1/2) = 9.0

r = torch.mean(v, 1)         # Size 3: Mean in dim 1
r = torch.mean(v, 1, True)   # Size 3x1 since keep dimension = True

r = torch.sum(v, 1)          # Sum over dim 1
r = torch.sum(v)

#### Comparison

In [28]:
# Size 3x3: Element-wise comparison
r = torch.eq(v,v)
# k-th element (start from 1) ascending order with corresponding index
r = torch.kthvalue(v,2)

r = torch.max(v,1)
r = torch.sort(v,1)
r = torch.topk(v,1)

m1 = torch.ones(3,5)
m2 = torch.ones(3,5)
v1 = torch.ones(3)

# Cross product, Size 3x5
r = torch.cross(m1,m2)
# Diagonal matrix, Size 3x3
r = torch.diag(v1)

# Histogram
torch.histc(torch.FloatTensor([1,2,1]),bins=4,min=0,max=3)

# Renormalize
r = torch.renorm(v, 1, 0, 1)

#### Matrix, vector products

In [29]:
# Matrix X vector, Size 2x4
mat = torch.randn(2,4)
vec = torch.randn(4)
r = torch.mv(mat, vec)

# Matrix + Matrix X vector, Size 2
M = torch.randn(2)
mat = torch.randn(2,3)
vec = torch.randn(3)
r = torch.addmv(M,mat,vec)

# Matrix x Matrix, Size 2x4
mat1 = torch.randn(2,3)
mat2 = torch.randn(3,4)
r = torch.mm(mat1,mat2)

# Matrix + Matrix X Matrix, Size 3x4
M = torch.randn(3,4)
mat1 = torch.randn(3,2)
mat2 = torch.randn(2,4)
r = torch.addmm(M,mat1,mat2)

# Dot product of 2 tensors
r = torch.dot(torch.Tensor([4,2]),torch.Tensor([3,1])) # 14

# Outer product of 2 vectors, Size 3x2
v1 = torch.arange(1,4)
v2 = torch.arange(1,3)
r = torch.ger(v1,v2)

# Batch Matrix x Matrix, Size 10x3x5
batch1 = torch.randn(10,3,4)
batch2 = torch.randn(10,4,5)
r = torch.bmm(batch1,batch2)

# Batch Matrix + Matrix x Matrix
# Performs a batch matrix-matrix product
# 3x4 + (5x3x4 X 5x4x2 ) -> 5x3x2
M = torch.randn(3,2)
batch1 = torch.randn(5,3,4)
batch2 = torch.randn(5,4,2)
r = torch.addbmm(M,batch1,batch2)

# Move Tensors to GPU
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y
print(r)

tensor([[ 3.0873,  0.0981],
        [ 6.9641, -0.6061],
        [-1.0203, -2.8441]])
